# This is the config file for ChestRestack.
# This config was generated for version 1.0

# You can delete this file to regenerate the default config on server reload.


sort-inventory: true

# whether new updates should be announced to admins and in the console.
# updating to the newest version is always recommended unless the new version is not compatible with your server.
check-for-updates: true